episodeLength: 20
compass: true
weather: false
map:
    size: 2000
    wall:
        height: 128
        block: 7
daylightCycle:
    do: false
    time: 6000
allow-reconnect: true
check-update: true
scoreboard: UHCey
kick-on-death:
    kick: false
    time: 30
